export const APP_ACTIONS = {
  FETCH_DATA: 'FETCH_DATA',
  FETCH_DATA_RESOLVED: 'FETCH_DATA_RESOLVED',
  FETCH_DATA_RESOLVING: 'FETCH_DATA_RESOLVING',
  FETCH_DATA_ERROR: 'FETCH_DATA_ERROR',
  FETCH_ANS: 'FETCH_ANS',
  FETCH_ANS_RESOLVED: 'FETCH_ANS_RESOLVED',
  FETCH_ANS_RESOLVING: 'FETCH_ANS_RESOLVING',
};
